check_contrast = true

[templates]
hyprland = { template = "hyprland", target = "~/.config/hypr/colors.conf" }
waybar = { template = "waybar", target = "~/.config/waybar/colors.css" }
alacritty = { template = "alacritty", target = "~/.config/alacritty/colors.toml" }
mako = { template = "mako", target = "~/.config/mako/config" }
rofi = { template = "rofi", target = "~/.config/rofi/themes/colors.rasi" }
