[general]
early-exit = true
corner-roundness = 12
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 1
save-after-copy = true
output-filename = "/Screenshot/%Y-%m-%d_%H:%M:%S.png"
